name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_docker_hub:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Echo Docker Hub Username
        run: echo ${{ secrets.DOCKER_USERNAME}}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Random Number Using GitHub Context
        id: random_number
        run: |
          # Generate a pseudo-random number using GitHub's run context
          random_number=$(( ( RANDOM % 10000 ) + 10000 ))  # Between 10000 and 19999
          echo "Generated random number: $random_number"
          echo "::set-output name=random_number::$random_number"
      - name: Echo current version
        run: echo  $new_version
      - name: Build Docker image
        id: build_image
        run: |
          docker  build -t ${{ secrets.DOCKER_USERNAME }}/ubuntu-debug-tools: $new_version -f  ./ubuntu-debug-tools.dockerfile .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ubuntu-debug-tools:$new_version

      - name: Logout from Docker Hub
        run: docker logout

      - name: End
        run: echo "Docker image pushed to Docker Hub successfully"
